#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
source "${SCRIPT_DIR}/env.sh"
source "${SCRIPT_DIR}/stage2-common.sh"

log() {
  printf '[firemarshal-build] %s\n' "$*"
}

die() {
  printf '[firemarshal-build][error] %s\n' "$*" >&2
  exit 1
}

usage() {
  cat <<'EOF'
Usage:
  bash scripts/build-firemarshal-images.sh [options]

Default:
  Clean, build, and install every FireMarshal workload JSON generated by
  scripts/package-firemarshal-workload.sh.

Inputs:
  $PYTORCH_CHIPYARD_WORKLOAD_DIR/*.json

Outputs:
  $FIREMARSHAL_IMAGE_DIR/<workload>/<workload>-bin
  $FIREMARSHAL_IMAGE_DIR/<workload>/<workload>.img
  $FIRESIM_WORKLOAD_DIR/<workload>.json

Notes:
  FireMarshal mounts rootfs images while applying overlays. It uses an allowed
  FireSim mount helper when available and otherwise falls back to guestmount;
  this wrapper does not require general sudo access.

Options:
  --workload=NAME  Build only this workload. May be repeated or comma-separated.
  --pending-only   Skip workloads with complete collected FireSim results.
  --reuse-shared-kernel-build
                   Do not deep-clean the shared Linux/OpenSBI build trees.
                   The default is a fresh build for reproducibility.
  -h, --help       Show this help.
EOF
}

selected_workloads=()
pending_only=0
fresh_shared_kernel_build="${PYTORCH_CHIPYARD_FRESH_FIREMARSHAL_KERNEL_BUILD:-1}"
while [[ "$#" -gt 0 ]]; do
  case "$1" in
    --workload)
      [[ "$#" -ge 2 ]] || die "--workload requires a value"
      IFS=, read -r -a requested_workloads <<<"$2"
      selected_workloads+=("${requested_workloads[@]}")
      shift 2
      ;;
    --workload=*)
      IFS=, read -r -a requested_workloads <<<"${1#--workload=}"
      selected_workloads+=("${requested_workloads[@]}")
      shift
      ;;
    --pending-only)
      pending_only=1
      shift
      ;;
    --reuse-shared-kernel-build)
      fresh_shared_kernel_build=0
      shift
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      die "unknown argument '$1'; pass --help for usage"
      ;;
  esac
done

[[ "${fresh_shared_kernel_build}" == "0" || "${fresh_shared_kernel_build}" == "1" ]] || \
  die "PYTORCH_CHIPYARD_FRESH_FIREMARSHAL_KERNEL_BUILD must be 0 or 1"

[[ -f "${FIREMARSHAL_DIR}/marshal" ]] || \
  die "FireMarshal is not initialized at ${FIREMARSHAL_DIR}; check CHIPYARD_DIR or FIREMARSHAL_DIR"
mkdir -p "${FIRESIM_DEPLOY_DIR}" "${FIRESIM_WORKLOAD_DIR}"
[[ -d "${PYTORCH_CHIPYARD_WORKLOAD_DIR}" ]] || \
  die "workload directory not found: ${PYTORCH_CHIPYARD_WORKLOAD_DIR}; run scripts/package-firemarshal-workload.sh first"

export TMPDIR="${TMPDIR:-$PYTORCH_CHIPYARD_FIREMARSHAL_TMP_DIR}"

mkdir -p \
  "${MARSHAL_MOUNT_DIR}" \
  "${LIBGUESTFS_CACHEDIR}" \
  "${LIBGUESTFS_TMPDIR}" \
  "${TMPDIR}" \
  "${MARSHAL_LOG_DIR}" \
  "${MARSHAL_RES_DIR}" \
  "${FIREMARSHAL_DIR}/runOutput" \
  "${FIREMARSHAL_DIR}/wlutil/generated" \
  "${FIREMARSHAL_IMAGE_DIR}" \
  "${FIRESIM_WORKLOAD_DIR}"

workload_jsons=()
if [[ "${#selected_workloads[@]}" -gt 0 ]]; then
  declare -A seen_workloads=()
  for workload in "${selected_workloads[@]}"; do
    [[ -n "${workload}" ]] || continue
    [[ "${workload}" =~ ^[A-Za-z0-9._-]+$ ]] || \
      die "invalid workload '${workload}'"
    [[ -z "${seen_workloads[${workload}]:-}" ]] || continue
    seen_workloads["${workload}"]=1
    workload_json="${PYTORCH_CHIPYARD_WORKLOAD_DIR}/${workload}.json"
    [[ -f "${workload_json}" ]] || \
      die "workload JSON not found: ${workload_json}"
    workload_jsons+=("${workload_json}")
  done
else
  while IFS= read -r -d '' workload_json; do
    workload_jsons+=("${workload_json}")
  done < <(find "${PYTORCH_CHIPYARD_WORKLOAD_DIR}" -maxdepth 1 -type f -name '*.json' ! -name '*base.json' -print0 | sort -z)
fi

should_collect_output_bin() {
  local workload="$1"

  case "${workload}" in
    gpt2-* | gpt-neo-* | opt-* | pythia-* | *tok*)
      return 1
      ;;
    *)
      return 0
      ;;
  esac
}

collected_result_complete() {
  local workload="$1"
  pc_stage2_result_complete \
    "${PYTORCH_CHIPYARD_FIGURE_RESULTS_WORKLOAD_DIR}" "${workload}"
}

if [[ "${pending_only}" -eq 1 ]]; then
  pending_jsons=()
  for workload_json in "${workload_jsons[@]}"; do
    workload="$(basename "${workload_json}" .json)"
    if collected_result_complete "${workload}"; then
      log "pending-only: skipping completed workload ${workload}"
    else
      pending_jsons+=("${workload_json}")
    fi
  done
  workload_jsons=("${pending_jsons[@]}")
fi

if [[ "${#workload_jsons[@]}" -eq 0 ]]; then
  if [[ "${pending_only}" -eq 1 ]]; then
    log "pending-only: no images need rebuilding"
    exit 0
  fi
  die "no workload JSON files found under ${PYTORCH_CHIPYARD_WORKLOAD_DIR}; run scripts/package-firemarshal-workload.sh first"
fi

marshal_cwd="$(mktemp -d "${TMPDIR%/}/marshal-cwd.XXXXXX")"
cleanup() {
  local status=$?
  local workload_json workload
  local -a cleanup_args=()

  trap - EXIT
  rm -rf -- "${marshal_cwd}"
  if [[ "${status}" -ne 0 ]]; then
    for workload_json in "${workload_jsons[@]}"; do
      workload="$(basename -- "${workload_json}" .json)"
      cleanup_args+=(--workload "${workload}")
    done
    [[ "${#cleanup_args[@]}" -gt 0 ]] || cleanup_args+=(--all)
    bash "${SCRIPT_DIR}/cleanup-runtime-artifacts.sh" "${cleanup_args[@]}" --final || \
      printf '[firemarshal-build][warn] failure cleanup did not complete\n' >&2
  fi
  exit "${status}"
}
trap cleanup EXIT

log "FireMarshal dir: ${FIREMARSHAL_DIR}"
log "workload dir: ${PYTORCH_CHIPYARD_WORKLOAD_DIR}"
log "image dir: ${FIREMARSHAL_IMAGE_DIR}"
log "FireSim workload dir: ${FIRESIM_WORKLOAD_DIR}"
log "cleaning/building/installing ${#workload_jsons[@]} workload(s)"

build_lock="${PYTORCH_CHIPYARD_FIREMARSHAL_BUILD_LOCK:-${FIREMARSHAL_DIR}/.pytorch-chipyard-build.lock}"
(
  umask 0002
  touch "${build_lock}"
)

(
  flock -x 9

  if [[ "${fresh_shared_kernel_build}" == "1" ]]; then
    linux_dir="${FIREMARSHAL_DIR}/boards/default/linux"
    opensbi_dir="${FIREMARSHAL_DIR}/boards/default/firmware/opensbi"
    [[ -f "${linux_dir}/Makefile" ]] || die "Linux source tree not found: ${linux_dir}"
    [[ -f "${opensbi_dir}/Makefile" ]] || die "OpenSBI source tree not found: ${opensbi_dir}"
    log "deep-cleaning shared Linux/OpenSBI build trees"
    make -C "${linux_dir}" ARCH=riscv mrproper
    make -C "${opensbi_dir}" clean
  fi

  cd "${marshal_cwd}"
  "${FIREMARSHAL_DIR}/marshal" --workdir "${PYTORCH_CHIPYARD_WORKLOAD_DIR}" clean "${workload_jsons[@]}"
  "${FIREMARSHAL_DIR}/marshal" --workdir "${PYTORCH_CHIPYARD_WORKLOAD_DIR}" build "${workload_jsons[@]}"
  "${FIREMARSHAL_DIR}/marshal" --workdir "${PYTORCH_CHIPYARD_WORKLOAD_DIR}" install "${workload_jsons[@]}"
) 9>>"${build_lock}"

log "done"
