#!/usr/bin/env python3
"""Materialize a user-local FireSim HWDB for bundled U250 artifacts."""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import tempfile
from typing import Any

import yaml


class PreparationError(RuntimeError):
    pass


def resolve_bundled_file(root: Path, value: Any, field: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise PreparationError(f"{field} must be a non-empty relative path")

    relative = Path(value)
    if relative.is_absolute():
        raise PreparationError(f"{field} must be relative to {root}: {value}")

    try:
        resolved = (root / relative).resolve(strict=True)
    except FileNotFoundError as error:
        raise PreparationError(f"{field} does not exist: {root / relative}") from error

    try:
        resolved.relative_to(root)
    except ValueError as error:
        raise PreparationError(f"{field} escapes the bitstream directory: {value}") from error

    if not resolved.is_file() or resolved.stat().st_size == 0:
        raise PreparationError(f"{field} is not a non-empty file: {resolved}")
    if not os.access(resolved, os.R_OK):
        raise PreparationError(f"{field} is not readable: {resolved}")
    return resolved.as_uri()


def load_hwdb(template: Path, bitstream_dir: Path) -> dict[str, Any]:
    try:
        with template.open("r", encoding="utf-8") as stream:
            hwdb = yaml.safe_load(stream)
    except (OSError, yaml.YAMLError) as error:
        raise PreparationError(f"could not load HWDB template {template}: {error}") from error

    if not isinstance(hwdb, dict) or not hwdb:
        raise PreparationError(f"HWDB template is not a non-empty mapping: {template}")

    for name, entry in hwdb.items():
        if not isinstance(name, str) or not isinstance(entry, dict):
            raise PreparationError(f"invalid HWDB entry: {name!r}")
        for field in ("bitstream_tar", "driver_tar"):
            entry[field] = resolve_bundled_file(
                bitstream_dir, entry.get(field), f"{name}.{field}"
            )
    return hwdb


def write_atomic(output: Path, hwdb: dict[str, Any]) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{output.name}.", dir=output.parent, text=True
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as stream:
            stream.write("# Generated by scripts/prepare-firesim-hwdb.py.\n")
            stream.write("# Do not edit; edit bitstreams/config_hwdb.yaml.in instead.\n\n")
            yaml.safe_dump(hwdb, stream, sort_keys=False)
        temporary.chmod(0o644)
        os.replace(temporary, output)
    finally:
        temporary.unlink(missing_ok=True)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--template", required=True, type=Path)
    parser.add_argument("--bitstream-dir", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        bitstream_dir = args.bitstream_dir.expanduser().resolve(strict=True)
        template = args.template.expanduser().resolve(strict=True)
        output = args.output.expanduser().resolve(strict=False)
        hwdb = load_hwdb(template, bitstream_dir)
        write_atomic(output, hwdb)
    except (OSError, PreparationError) as error:
        print(f"[prepare-firesim-hwdb][FAIL] {error}")
        return 1

    print(f"FIRESIM_HWDB_PATH={output}")
    print(f"FIRESIM_HWDB_CONFIGS={len(hwdb)}")
    print("FIRESIM_HWDB_PREPARE_STATUS=PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
