#!/usr/bin/env python3
"""Materialize a user-local FireSim HWDB for bundled U250 artifacts."""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import tempfile
from typing import Any

import yaml


class PreparationError(RuntimeError):
    pass


BUNDLED_HW_CONFIGS = {
    "alveo_u250_firesim_fp8x8_gemmini_boom_2core_no_nic": (
        "WithDefaultFireSimBridges_WithFireSimConfigTweaks_chipyard."
        "DualFP8x8GemminiBoomConfig"
    ),
    "alveo_u250_firesim_fp8x8_gemmini_rocket_2core_no_nic": (
        "WithDefaultFireSimBridges_WithFireSimConfigTweaks_chipyard."
        "DualFP8x8GemminiRocketConfig"
    ),
    "alveo_u250_firesim_fp8x8_gemmini_rocket_4core_no_nic": (
        "WithDefaultFireSimBridges_WithFireSimConfigTweaks_chipyard."
        "QuadFP8x8GemminiRocketConfig"
    ),
    "alveo_u250_firesim_minv128d64_rocket_2core_no_nic": (
        "WithDefaultFireSimBridges_WithFireSimConfigTweaks_chipyard."
        "MINV128D64Rocket2Config"
    ),
    "alveo_u250_firesim_minv128d64_rocket_4core_no_nic": (
        "WithDefaultFireSimBridges_WithFireSimConfigTweaks_chipyard."
        "MINV128D64Rocket4Config"
    ),
    "alveo_u250_firesim_minv128d64_rocket_4core_no_nic_30mhz": (
        "WithDefaultFireSimBridges_WithFireSimConfigTweaks_chipyard."
        "MINV128D64Rocket4Config"
    ),
    "alveo_u250_firesim_minv128d64_rocket_8core_no_nic_30mhz": (
        "WithDefaultFireSimBridges_WithFireSimConfigTweaks_chipyard."
        "MINV128D64Rocket8Config"
    ),
    "alveo_u250_firesim_rocket_16core_no_nic": (
        "WithDefaultFireSimBridges_WithFireSimConfigTweaks_chipyard."
        "Rocket16Config"
    ),
}


def resolve_bundled_file(root: Path, value: Any, field: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise PreparationError(f"{field} must be a non-empty relative path")

    relative = Path(value)
    if relative.is_absolute():
        raise PreparationError(f"{field} must be relative to {root}: {value}")

    try:
        resolved = (root / relative).resolve(strict=True)
    except FileNotFoundError as error:
        raise PreparationError(f"{field} does not exist: {root / relative}") from error

    try:
        resolved.relative_to(root)
    except ValueError as error:
        raise PreparationError(f"{field} escapes the bitstream directory: {value}") from error

    if not resolved.is_file() or resolved.stat().st_size == 0:
        raise PreparationError(f"{field} is not a non-empty file: {resolved}")
    if not os.access(resolved, os.R_OK):
        raise PreparationError(f"{field} is not readable: {resolved}")
    return resolved.as_uri()


def load_hwdb(bitstream_dir: Path) -> dict[str, Any]:
    hwdb: dict[str, Any] = {}
    for name, target_config in BUNDLED_HW_CONFIGS.items():
        hwdb[name] = {
            "deploy_quintuplet": {
                "design": "Firesim",
                "target_config": target_config,
                "platform": "xilinx_alveo_u250",
                "platform_config": "BaseXilinxAlveoU250Config",
            },
            "bitstream_tar": resolve_bundled_file(
                bitstream_dir,
                f"{name}/firesim.tar.gz",
                f"{name}.bitstream_tar",
            ),
            "driver_tar": resolve_bundled_file(
                bitstream_dir,
                f"{name}/driver-bundle.tar.gz",
                f"{name}.driver_tar",
            ),
            "post_build_hook": None,
            "custom_runtime_config": None,
        }
    return hwdb


def write_atomic(output: Path, hwdb: dict[str, Any]) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{output.name}.", dir=output.parent, text=True
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as stream:
            stream.write("# Generated by scripts/prepare-firesim-hwdb.py.\n")
            stream.write("# Bundled configurations are defined in that script.\n\n")
            yaml.safe_dump(hwdb, stream, sort_keys=False)
        temporary.chmod(0o644)
        os.replace(temporary, output)
    finally:
        temporary.unlink(missing_ok=True)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--bitstream-dir", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        bitstream_dir = args.bitstream_dir.expanduser().resolve(strict=True)
        output = args.output.expanduser().resolve(strict=False)
        hwdb = load_hwdb(bitstream_dir)
        write_atomic(output, hwdb)
    except (OSError, PreparationError) as error:
        print(f"[prepare-firesim-hwdb][FAIL] {error}")
        return 1

    print(f"FIRESIM_HWDB_PATH={output}")
    print(f"FIRESIM_HWDB_CONFIGS={len(hwdb)}")
    print("FIRESIM_HWDB_PREPARE_STATUS=PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
