#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
source "${SCRIPT_DIR}/env.sh"
source "${SCRIPT_DIR}/stage2-common.sh"

log() {
  printf '[firesim-run] %s\n' "$*"
}

warn() {
  printf '[firesim-run][warn] %s\n' "$*" >&2
}

die() {
  printf '[firesim-run][error] %s\n' "$*" >&2
  exit 1
}

usage() {
  cat <<'EOF'
Usage:
  bash scripts/run-firesim-workloads.sh [options]

Default:
  Run every FireSim workload generated by scripts/package-firemarshal-workload.sh,
  then preserve only model.log and autotune.log under
  scripts/figures/results-workload/<workload>/. FireSim/FireMarshal runtime
  files and logs are removed after the run, whether it succeeds or fails.

Options:
  --workload=NAME      Run/collect one workload. May be repeated or comma-separated.
  --preflight-only     Validate selected HWDB artifacts, then exit without a run.
  --resume             Skip workloads that already have both durable logs.
  --resume-from=NAME   Start from NAME in the
                       selected/discovered workload order.
  --rvv-panic-retries=N|unlimited
                       Retry an RVV workload after a detected kernel panic or
                       corrupt UART. Default: 0; unlimited must be explicit.
  -h, --help           Show this help.

Environment:
  PYTORCH_CHIPYARD_BITSTREAM_DIR             Bundled U250 runtime artifacts.
                                             Default: $WORKSPACE/bitstreams
  FIRESIM_HWDB_PATH                          Optional external HWDB override.
                                             By default a user-local HWDB
                                             is generated from the bundle.
  PYTORCH_CHIPYARD_FPGA_DB                   Default: /opt/firesim-db.json
  FIRESIM_RUNS_DIR                          Per-account FireSim run directory.
  PYTORCH_CHIPYARD_FIRESIM_RUNTIME_DIR      Generated config_runtime files.
  PYTORCH_CHIPYARD_RESULTS_WORKLOAD_DIR     FireSim results-workload directory.
  PYTORCH_CHIPYARD_FIGURE_RESULTS_WORKLOAD_DIR
                                             Collected result directory.
  PYTORCH_CHIPYARD_LOG_DIR                  Current stage2 log directory.
  PYTORCH_CHIPYARD_FIRESIM_PYTHON           Optional FireSim/HWDB Python
                                             override. Default:
                                             $CHIPYARD_DIR/.conda-env/bin/python3.
  PYTORCH_CHIPYARD_FIRESIM_RUN_FARM_HOST    Default: localhost
  PYTORCH_CHIPYARD_FIRESIM_RUN_FARM_SPEC    Default: one_fpgas_spec
  PYTORCH_CHIPYARD_CLEAN_FIRESIM_RUNS_DIR=0 Skip clearing FIRESIM_RUNS_DIR.
  PYTORCH_CHIPYARD_KEEP_RUNFARM=1           Skip terminaterunfarm.
  PYTORCH_CHIPYARD_FIRESIM_HW_CONFIG_OVERRIDES
                                             Comma-separated workload=hw_config list.

Failure handling:
  While runworkload is active, UART logs are monitored for guest failures such
  as kernel panics, oopses, signals, and FireSim failure markers. The active
  run is terminated immediately. RVV kernel failures are cleaned up with
  firesim kill and retried with a new run farm; other failures stop Stage 2.

Per-workload hardware override:
  PYTORCH_CHIPYARD_FIRESIM_HW_CONFIG_<WORKLOAD>

Example:
  PYTORCH_CHIPYARD_FIRESIM_HW_CONFIG_RESNET50_GEMMINI_4CORE=alveo_u250_firesim_fp8x8_gemmini_rocket_4core_no_nic \
    bash scripts/run-firesim-workloads.sh --workload=resnet50-gemmini-4core
EOF
}

validate_name() {
  local label="$1"
  local value="$2"
  [[ "${value}" =~ ^[A-Za-z0-9._-]+$ ]] || \
    die "invalid ${label} '${value}'; use only letters, numbers, '.', '_', and '-'"
}

require_file() {
  local path="$1"
  [[ -f "${path}" ]] || die "missing required file: ${path}"
}

require_dir() {
  local path="$1"
  [[ -d "${path}" ]] || die "missing required directory: ${path}"
}

clean_firesim_runs_dir() {
  local dir="${FIRESIM_RUNS_DIR}"
  local enabled="${PYTORCH_CHIPYARD_CLEAN_FIRESIM_RUNS_DIR:-1}"

  [[ "${enabled}" == "1" ]] || return 0
  [[ -n "${dir}" && "${dir}" != "/" ]] || die "refusing to clean unsafe FIRESIM_RUNS_DIR='${dir}'"
  mkdir -p "${dir}"
  find "${dir}" -mindepth 1 -maxdepth 1 -exec rm -rf -- {} +
  log "cleaned FIRESIM_RUNS_DIR: ${dir}"
}

clean_completed_firesim_run() {
  local keep_runfarm="${PYTORCH_CHIPYARD_KEEP_RUNFARM:-${KEEP_RUNFARM:-0}}"

  if [[ "${keep_runfarm}" == "1" ]]; then
    log "preserving FIRESIM_RUNS_DIR because the run farm was kept"
    return 0
  fi
  clean_firesim_runs_dir
}

clean_dir_contents() {
  local label="$1"
  local dir="$2"

  [[ -n "${dir}" && "${dir}" != "/" ]] || die "refusing to clean unsafe ${label}='${dir}'"
  mkdir -p "${dir}"
  find "${dir}" -mindepth 1 -maxdepth 1 -exec rm -rf -- {} +
  log "cleaned ${label}: ${dir}"
}

clean_collected_results() {
  mkdir -p "${PYTORCH_CHIPYARD_FIGURE_RESULTS_WORKLOAD_DIR}"
  log "preserving durable model.log/autotune.log results"
}

yaml_quote() {
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  printf '"%s"' "${value}"
}

split_workload_arg() {
  local value="$1"
  local item
  local -a items

  IFS=, read -r -a items <<<"${value}"
  for item in "${items[@]}"; do
    [[ -n "${item}" ]] || continue
    validate_name "workload" "${item}"
    SELECTED_WORKLOADS+=("${item}")
  done
}

discover_workloads() {
  local json path base workload

  [[ -d "${PYTORCH_CHIPYARD_WORKLOAD_DIR}" ]] || return 0
  while IFS= read -r path; do
    base="$(basename "${path}")"
    workload="${base%.json}"
    case "${workload}" in
      br-base | *base)
        continue
        ;;
    esac
    validate_name "workload" "${workload}"
    printf '%s\n' "${workload}"
  done < <(find "${PYTORCH_CHIPYARD_WORKLOAD_DIR}" -maxdepth 1 -type f -name '*.json' -print | sort -V)
}

unique_workloads() {
  local -A seen=()
  local workload

  for workload in "$@"; do
    [[ -n "${seen[${workload}]:-}" ]] && continue
    seen["${workload}"]=1
    printf '%s\n' "${workload}"
  done
}

elf_has_openmp_symbols() {
  local elf_path="$1"

  LC_ALL=C readelf -Ws "${elf_path}" 2>/dev/null | awk '
    NF >= 8 {
      name = $8
      if (name ~ /^(GOMP_|omp_)/ || name ~ /_omp_fn/) found = 1
    }
    END { exit(found ? 0 : 1) }
  '
}

require_boom_flex_kernel_package() {
  local workload="$1"
  local runner image elf bootbinary workload_json linux_config

  case "${workload}" in
    opt-boom-gemmini-flash-*tok-1core | opt-boom-gemmini-window-*tok-1core) ;;
    *) return 0 ;;
  esac

  runner="${PYTORCH_CHIPYARD_WORKLOAD_DIR}/overlay-${workload}/root/llm/run_${workload}.sh"
  elf="${PYTORCH_CHIPYARD_WORKLOAD_DIR}/overlay-${workload}/root/llm/${workload}/model-1core.elf"
  image="${FIREMARSHAL_IMAGE_DIR}/${workload}/${workload}.img"
  bootbinary="${FIREMARSHAL_IMAGE_DIR}/${workload}/${workload}-bin"
  workload_json="${PYTORCH_CHIPYARD_WORKLOAD_DIR}/${workload}.json"
  linux_config="${PYTORCH_CHIPYARD_WORKLOAD_DIR}/.pytorch-chipyard-${workload}-linux-config"
  require_file "${runner}"
  grep -Fq -- '--kernel-only=flex_attention' "${runner}" || \
    die "${workload} was packaged for full-model execution; rerun Stage 2 to regenerate its ELF, package, and image"
  grep -Fq -- '[runner] openmp=disabled' "${runner}" || \
    die "${workload} runner does not disable OpenMP; rebuild its ELF and repackage the workload"
  if grep -Eq 'OMP_|GOMP_' "${runner}"; then
    die "${workload} runner still configures OpenMP; repackage the workload"
  fi
  command -v readelf >/dev/null 2>&1 || \
    die "readelf is required to verify the ${workload} ELF"
  require_file "${elf}"
  if elf_has_openmp_symbols "${elf}"; then
    die "${workload} ELF still contains OpenMP code; rebuild it with the Spike executable option"
  fi
  if LC_ALL=C readelf -d "${elf}" 2>/dev/null | grep -Fqi 'libgomp'; then
    die "${workload} ELF still links libgomp; rebuild it with the Spike executable option"
  fi
  require_file "${workload_json}"
  require_file "${linux_config}"
  grep -Fq 'CONFIG_CMDLINE="maxcpus=1 console=ttySIF0,3686400 earlycon"' "${linux_config}" || \
    die "${workload} Linux config does not keep BOOM hart 1 offline; repackage the workload"
  grep -Fq "\"config\": \"$(basename "${linux_config}")\"" "${workload_json}" || \
    die "${workload} workload JSON does not reference its maxcpus=1 Linux config; repackage the workload"
  require_file "${image}"
  require_file "${bootbinary}"
  LC_ALL=C grep -aFq 'maxcpus=1 console=ttySIF0,3686400 earlycon' "${bootbinary}" || \
    die "${workload} boot binary was not built with maxcpus=1; rebuild its FireMarshal image"
  [[ "${image}" -nt "${runner}" ]] || \
    die "${workload} FireMarshal image predates its kernel-only runner; rebuild the image before FireSim execution"
}

load_workloads() {
  local workloads=()

  if [[ "${#SELECTED_WORKLOADS[@]}" -gt 0 ]]; then
    mapfile -t workloads < <(unique_workloads "${SELECTED_WORKLOADS[@]}")
  else
    mapfile -t workloads < <(discover_workloads)
  fi

  [[ "${#workloads[@]}" -gt 0 ]] || \
    die "no packaged workloads found under ${PYTORCH_CHIPYARD_WORKLOAD_DIR}; run scripts/package-firemarshal-workload.sh first"

  WORKLOADS=("${workloads[@]}")
}

require_installed_workload_image() {
  local workload="$1"
  local image_dir="${FIREMARSHAL_IMAGE_DIR}/${workload}"

  [[ -s "${image_dir}/${workload}.img" ]] || \
    die "${workload} FireMarshal image is missing: ${image_dir}/${workload}.img; build this workload image before FireSim execution"
  [[ -s "${image_dir}/${workload}-bin" ]] || \
    die "${workload} FireMarshal boot binary is missing: ${image_dir}/${workload}-bin; build this workload image before FireSim execution"
}

apply_resume_filters() {
  local workload
  local found=0
  local filtered=()
  local pending=()

  if [[ -n "${RESUME_FROM}" ]]; then
    for workload in "${WORKLOADS[@]}"; do
      if [[ "${workload}" == "${RESUME_FROM}" ]]; then
        found=1
      fi
      if [[ "${found}" -eq 1 ]]; then
        filtered+=("${workload}")
      fi
    done

    [[ "${found}" -eq 1 ]] || \
      die "resume workload '${RESUME_FROM}' was not found in the selected/discovered workload list"

    WORKLOADS=("${filtered[@]}")
    log "resume-from ${RESUME_FROM}: ${#WORKLOADS[@]} workload(s) remaining"
  fi

  if [[ "${RESUME_MODE}" -eq 1 ]]; then
    for workload in "${WORKLOADS[@]}"; do
      if collected_result_complete "${workload}"; then
        log "resume: skipping completed workload ${workload}"
      else
        pending+=("${workload}")
      fi
    done

    WORKLOADS=("${pending[@]}")
    if [[ "${#WORKLOADS[@]}" -eq 0 ]]; then
      log "resume: no pending workloads"
      return 0
    fi
    log "resume: ${#WORKLOADS[@]} pending workload(s)"
  fi
}

validate_pending_workload_packages() {
  local workload

  [[ "${PREFLIGHT_ONLY}" != "1" ]] || return 0
  for workload in "${WORKLOADS[@]}"; do
    require_file "${PYTORCH_CHIPYARD_WORKLOAD_DIR}/${workload}.json"
    require_file "${FIRESIM_WORKLOAD_DIR}/${workload}.json"
    require_installed_workload_image "${workload}"
    require_boom_flex_kernel_package "${workload}"
  done
}

core_for_workload() {
  local workload="$1"

  if [[ "${workload}" =~ (^|-)([0-9]+)core($|-) ]]; then
    printf '%s\n' "${BASH_REMATCH[2]}"
    return 0
  fi

  return 1
}

is_llm_workload() {
  local workload="$1"

  case "${workload}" in
    gpt2-* | gpt-neo-* | opt-* | pythia-* | *tok*)
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

should_collect_output_bin() {
  local workload="$1"

  if is_llm_workload "${workload}"; then
    return 1
  fi

  return 0
}

collected_result_dir() {
  local workload="$1"

  printf '%s/%s\n' "${PYTORCH_CHIPYARD_FIGURE_RESULTS_WORKLOAD_DIR}" "${workload}"
}

collected_result_complete() {
  local workload="$1"
  pc_stage2_result_complete \
    "${PYTORCH_CHIPYARD_FIGURE_RESULTS_WORKLOAD_DIR}" "${workload}"
}

contains_tag() {
  local workload="$1"
  local tag="$2"

  case "-${workload}-" in
    *-"${tag}"-*)
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

env_suffix_for_workload() {
  local workload="$1"
  local suffix

  suffix="${workload^^}"
  suffix="${suffix//[^A-Z0-9_]/_}"
  printf '%s\n' "${suffix}"
}

override_hw_config_for() {
  local workload="$1"
  local suffix var_name overrides pair key value

  suffix="$(env_suffix_for_workload "${workload}")"
  var_name="PYTORCH_CHIPYARD_FIRESIM_HW_CONFIG_${suffix}"
  if [[ -n "${!var_name:-}" ]]; then
    printf '%s\n' "${!var_name}"
    return 0
  fi

  overrides="${PYTORCH_CHIPYARD_FIRESIM_HW_CONFIG_OVERRIDES:-}"
  [[ -n "${overrides}" ]] || return 1

  IFS=, read -r -a pairs <<<"${overrides}"
  for pair in "${pairs[@]}"; do
    key="${pair%%=*}"
    value="${pair#*=}"
    [[ "${key}" == "${workload}" && "${value}" != "${pair}" && -n "${value}" ]] || continue
    printf '%s\n' "${value}"
    return 0
  done

  return 1
}

required_hw_config_for() {
  local workload="$1"

  case "${workload}" in
    opt-boom-gemmini-flash-*tok-1core | opt-boom-gemmini-window-*tok-1core)
      printf '%s\n' "alveo_u250_firesim_fp8x8_gemmini_boom_2core_no_nic"
      ;;
    alexnet-rvv-2core | squeezenet-rvv-2core)
      printf '%s\n' "alveo_u250_firesim_minv128d64_rocket_2core_no_nic"
      ;;
    mobilenetv2-rvv-2core | resnet50-rvv-2core)
      printf '%s\n' "alveo_u250_firesim_minv128d64_rocket_4core_no_nic_30mhz"
      ;;
    squeezenet-rvv-4core)
      printf '%s\n' "alveo_u250_firesim_minv128d64_rocket_4core_no_nic_30mhz"
      ;;
    alexnet-rvv-4core | mobilenetv2-rvv-4core | resnet50-rvv-4core)
      printf '%s\n' "alveo_u250_firesim_minv128d64_rocket_8core_no_nic_30mhz"
      ;;
    *)
      return 1
      ;;
  esac
}

rvv_success_profile_for() {
  local workload="$1"

  case "${workload}" in
    smoke-gemm-rvv-4core)
      printf '%s\n' '{0},{1},{2},{3}|0 1 2 3|ACTIVE|INFINITE|0|'
      ;;
    alexnet-rvv-2core)
      printf '%s\n' '{0},{1}|0 1|ACTIVE|INFINITE|0|'
      ;;
    alexnet-rvv-4core)
      printf '%s\n' '{4},{5},{6},{7}|4 5 6 7|ACTIVE|INFINITE|1|4-7'
      ;;
    mobilenetv2-rvv-2core)
      printf '%s\n' '{2},{3}|2 3|ACTIVE|INFINITE|0|'
      ;;
    mobilenetv2-rvv-4core)
      printf '%s\n' '{0},{1},{6},{7}|0 1 6 7|ACTIVE|INFINITE|1|0-1,6-7'
      ;;
    resnet50-rvv-2core)
      printf '%s\n' '{0},{1}|0 1|ACTIVE|INFINITE|1|0-1'
      ;;
    resnet50-rvv-4core)
      printf '%s\n' '{4},{5},{6},{7}|4 5 6 7|ACTIVE|INFINITE|1|4-7'
      ;;
    squeezenet-rvv-2core)
      printf '%s\n' '{0},{1}|0 1|ACTIVE|INFINITE|0|'
      ;;
    squeezenet-rvv-4core)
      printf '%s\n' '{0},{1},{2},{3}|0 1 2 3|PASSIVE|0|0|'
      ;;
    *)
      return 1
      ;;
  esac
}

validate_rvv_success_package() {
  local workload="$1"
  local profile expected_places expected_affinity expected_wait expected_spin
  local requires_hz100 expected_worker runner workload_json linux_fragment
  local linux_config image bootbinary

  contains_tag "${workload}" "rvv" || return 0

  profile="$(rvv_success_profile_for "${workload}")" || \
    die "${workload} has no validated RVV success profile"
  IFS='|' read -r expected_places expected_affinity expected_wait expected_spin \
    requires_hz100 expected_worker <<<"${profile}"

  runner="$(find "${PYTORCH_CHIPYARD_WORKLOAD_DIR}/overlay-${workload}" \
    -type f -name "run_${workload}.sh" -print -quit 2>/dev/null || true)"
  workload_json="${PYTORCH_CHIPYARD_WORKLOAD_DIR}/${workload}.json"
  linux_fragment="${PYTORCH_CHIPYARD_WORKLOAD_DIR}/.pytorch-chipyard-${workload}-linux-config"
  linux_config="${FIREMARSHAL_IMAGE_DIR}/${workload}/linux_config"
  image="${FIREMARSHAL_IMAGE_DIR}/${workload}/${workload}.img"
  bootbinary="${FIREMARSHAL_IMAGE_DIR}/${workload}/${workload}-bin"

  [[ -n "${runner}" ]] || \
    die "${workload} packaged runner is missing; rerun package-firemarshal-workload.sh"
  require_file "${workload_json}"
  require_file "${image}"
  require_file "${bootbinary}"

  grep -Fqx "export OMP_PLACES=\"${expected_places}\"" "${runner}" || \
    die "${workload} runner does not use validated OMP_PLACES=${expected_places}; repackage and rebuild it"
  grep -Fqx "export GOMP_CPU_AFFINITY=\"${expected_affinity}\"" "${runner}" || \
    die "${workload} runner does not use validated GOMP_CPU_AFFINITY=${expected_affinity}; repackage and rebuild it"
  grep -Fqx "export OMP_WAIT_POLICY=${expected_wait}" "${runner}" || \
    die "${workload} runner does not use validated OMP_WAIT_POLICY=${expected_wait}; repackage and rebuild it"
  grep -Fqx "export GOMP_SPINCOUNT=${expected_spin}" "${runner}" || \
    die "${workload} runner does not use validated GOMP_SPINCOUNT=${expected_spin}; repackage and rebuild it"

  if [[ "${requires_hz100}" == "1" ]]; then
    require_file "${linux_fragment}"
    require_file "${linux_config}"
    grep -Fq "\"linux\": {\"config\": \"$(basename "${linux_fragment}")\"}" "${workload_json}" || \
      die "${workload} FireMarshal JSON does not select its stable Linux fragment; repackage and rebuild it"
    grep -Fqx 'CONFIG_HZ=100' "${linux_config}" || \
      die "${workload} boot binary was not built with CONFIG_HZ=100; rebuild its FireMarshal image"
    grep -Fqx 'CONFIG_NO_HZ_FULL=y' "${linux_config}" || \
      die "${workload} boot binary was not built with CONFIG_NO_HZ_FULL=y; rebuild its FireMarshal image"
    grep -Fq "nohz_full=${expected_worker}" "${linux_config}" || \
      die "${workload} kernel command line does not isolate workers ${expected_worker}; rebuild its FireMarshal image"
    grep -Fq '[runner] rvv_stable_profile=hz100-nohz-full-fifo-v1' "${runner}" || \
      die "${workload} runner is missing the validated RVV runtime tuning; repackage and rebuild it"
    grep -Fq "taskset -c ${expected_worker} chrt -f 1 ./model-" "${runner}" || \
      die "${workload} runner is missing taskset/SCHED_FIFO for workers ${expected_worker}; repackage and rebuild it"
    grep -Fq 'sysctl -w kernel.sched_rt_runtime_us=-1' "${runner}" || \
      die "${workload} runner does not disable RT throttling; repackage and rebuild it"
  fi
}

infer_hw_config() {
  local workload="$1"
  local core override required

  if required="$(required_hw_config_for "${workload}")"; then
    if override="$(override_hw_config_for "${workload}")" && \
        [[ "${override}" != "${required}" ]]; then
      die "${workload} requires hardware config '${required}', but an environment override selected '${override}'"
    fi
    printf '%s\n' "${required}"
    return 0
  fi

  if override_hw_config_for "${workload}"; then
    return 0
  fi

  core="$(core_for_workload "${workload}")" || \
    die "could not infer core count from workload '${workload}'"

  if contains_tag "${workload}" "boom"; then
    case "${core}" in
      1) printf '%s\n' "alveo_u250_firesim_fp8x8_gemmini_boom_2core_no_nic" ;;
      2) printf '%s\n' "alveo_u250_firesim_fp8x8_gemmini_boom_2core_no_nic" ;;
      4) printf '%s\n' "alveo_u250_firesim_fp8x8_gemmini_boom_4core_no_nic" ;;
      *) die "no BOOM hardware config mapping for ${workload}" ;;
    esac
  elif contains_tag "${workload}" "gemmini"; then
    case "${core}" in
      2) printf '%s\n' "alveo_u250_firesim_fp8x8_gemmini_rocket_2core_no_nic" ;;
      4) printf '%s\n' "alveo_u250_firesim_fp8x8_gemmini_rocket_4core_no_nic" ;;
      *) die "no Gemmini hardware config mapping for ${workload}" ;;
    esac
  elif contains_tag "${workload}" "rvv"; then
    case "${core}" in
      1) printf '%s\n' "alveo_u250_firesim_minv128d64_rocket_4core_no_nic" ;;
      2)
        if [[ "${workload}" == "mobilenetv2-rvv-2core" ]]; then
          printf '%s\n' "alveo_u250_firesim_minv128d64_rocket_4core_no_nic_30mhz"
        else
          printf '%s\n' "alveo_u250_firesim_minv128d64_rocket_2core_no_nic"
        fi
        ;;
      4)
        printf '%s\n' "alveo_u250_firesim_minv128d64_rocket_8core_no_nic_30mhz"
        ;;
      *) die "no RVV hardware config mapping for ${workload}" ;;
    esac
  elif contains_tag "${workload}" "rocket"; then
    printf '%s\n' "alveo_u250_firesim_rocket_16core_no_nic"
  elif contains_tag "${workload}" "scalar"; then
    printf '%s\n' "alveo_u250_firesim_rocket_16core_no_nic"
  elif is_llm_workload "${workload}"; then
    case "${core}" in
      2) printf '%s\n' "alveo_u250_firesim_fp8x8_gemmini_rocket_2core_no_nic" ;;
      4) printf '%s\n' "alveo_u250_firesim_rocket_16core_no_nic" ;;
      *) die "no LLM fallback hardware config mapping for ${workload}" ;;
    esac
  elif [[ "${core}" == "16" ]]; then
    printf '%s\n' "alveo_u250_firesim_rocket_16core_no_nic"
  else
    die "could not infer hardware config for workload '${workload}'; set PYTORCH_CHIPYARD_FIRESIM_HW_CONFIG_$(env_suffix_for_workload "${workload}")"
  fi
}

validate_required_hw_config() {
  local workload="$1"
  local hw_config="$2"
  local required

  required="$(required_hw_config_for "${workload}")" || return 0
  [[ "${hw_config}" == "${required}" ]] || \
    die "${workload} must use hardware config '${required}', got '${hw_config}'"
}

require_hw_config() {
  local hw_config="$1"
  local validator="${SCRIPT_DIR}/validate-firesim-hwdb.py"

  require_file "${FIRESIM_HWDB_PATH}"
  require_file "${FIRESIM_BUILD_RECIPES_PATH}"
  require_file "${validator}"

  "${FIRESIM_PYTHON}" "${validator}" \
    --hwdb "${FIRESIM_HWDB_PATH}" \
    --config "${hw_config}" || \
    die "hardware artifact preflight failed for '${hw_config}'"
}

resolve_firesim_python() {
  local chipyard_python="${CHIPYARD_DIR}/.conda-env/bin/python3"
  local python_bin="${PYTORCH_CHIPYARD_FIRESIM_PYTHON:-${chipyard_python}}"

  [[ -x "${python_bin}" ]] || \
    die "FireSim Python interpreter is not executable: ${python_bin}; expected the hk_chipyard environment at ${chipyard_python}"
  printf '%s\n' "${python_bin}"
}

prepare_firesim_hwdb() {
  local generator="${SCRIPT_DIR}/prepare-firesim-hwdb.py"
  local legacy_hwdb="${FIRESIM_DIR}/deploy/config_hwdb.yaml"

  if [[ -n "${FIRESIM_HWDB_PATH:-}" && "${FIRESIM_HWDB_PATH}" != "${legacy_hwdb}" ]]; then
    require_file "${FIRESIM_HWDB_PATH}"
    log "using external FireSim HWDB: ${FIRESIM_HWDB_PATH}"
    return 0
  fi
  if [[ "${FIRESIM_HWDB_PATH:-}" == "${legacy_hwdb}" ]]; then
    log "replacing legacy shared HWDB with the bundled artifact HWDB"
  fi

  require_dir "${PYTORCH_CHIPYARD_BITSTREAM_DIR}"
  require_file "${PYTORCH_CHIPYARD_HWDB_TEMPLATE}"
  require_file "${generator}"
  mkdir -p "$(dirname -- "${PYTORCH_CHIPYARD_GENERATED_HWDB_PATH}")"
  "${FIRESIM_PYTHON}" "${generator}" \
    --template "${PYTORCH_CHIPYARD_HWDB_TEMPLATE}" \
    --bitstream-dir "${PYTORCH_CHIPYARD_BITSTREAM_DIR}" \
    --output "${PYTORCH_CHIPYARD_GENERATED_HWDB_PATH}" || \
    die "failed to prepare the bundled FireSim HWDB"
  export FIRESIM_HWDB_PATH="${PYTORCH_CHIPYARD_GENERATED_HWDB_PATH}"
  require_file "${FIRESIM_HWDB_PATH}"
  log "generated FireSim HWDB: ${FIRESIM_HWDB_PATH}"
}

generate_runtime_config() {
  local workload="$1"
  local hw_config="$2"
  local fpga_db="$3"
  local runtime="${PYTORCH_CHIPYARD_FIRESIM_RUNTIME_DIR}/config_runtime_${workload}.yaml"

  mkdir -p "${PYTORCH_CHIPYARD_FIRESIM_RUNTIME_DIR}" "${FIRESIM_RUNS_DIR}"

  cat >"${runtime}" <<EOF
# Auto-generated by scripts/run-firesim-workloads.sh

run_farm:
  #jseo: Recipes remain in the shared install even when deploy state is private.
  base_recipe: $(yaml_quote "${FIRESIM_DIR}/deploy/run-farm-recipes/externally_provisioned.yaml")
  recipe_arg_overrides:
    default_platform: XilinxAlveoU250InstanceDeployManager
    default_simulation_dir: $(yaml_quote "${FIRESIM_RUNS_DIR}")
    default_fpga_db: $(yaml_quote "${fpga_db}")
    run_farm_hosts_to_use:
        - $(yaml_quote "${PYTORCH_CHIPYARD_FIRESIM_RUN_FARM_HOST}"): ${PYTORCH_CHIPYARD_FIRESIM_RUN_FARM_SPEC}

metasimulation:
  metasimulation_enabled: false
  metasimulation_host_simulator: verilator
  metasimulation_only_plusargs: "+fesvr-step-size=128 +max-cycles=100000000"
  metasimulation_only_vcs_plusargs: "+vcs+initreg+0 +vcs+initmem+0"

target_config:
    topology: no_net_config
    no_net_num_nodes: 1
    link_latency: 6405
    switching_latency: 10
    net_bandwidth: 200
    profile_interval: -1
    default_hw_config: ${hw_config}
    plusarg_passthrough: ""

tracing:
    enable: no
    output_format: 0
    selector: 1
    start: 0
    end: -1

autocounter:
    read_rate: 0

workload:
    workload_name: ${workload}.json
    terminate_on_completion: yes
    suffix_tag: ${workload}

host_debug:
    zero_out_dram: no
    disable_synth_asserts: no

synth_print:
    start: 0
    end: -1
    cycle_prefix: yes
EOF

  printf '%s\n' "${runtime}"
}

latest_result_dir() {
  local workload="$1"
  local marker="${2:-}"
  local newer_args=()

  [[ -d "${PYTORCH_CHIPYARD_RESULTS_WORKLOAD_DIR}" ]] || return 1
  if [[ -n "${marker}" ]]; then
    newer_args=(-newer "${marker}")
  fi

  find "${PYTORCH_CHIPYARD_RESULTS_WORKLOAD_DIR}" \
    -maxdepth 2 \
    -type d \
    -name "${workload}0" \
    "${newer_args[@]}" \
    -printf '%T@ %p\n' 2>/dev/null | \
    sort -nr | \
    head -n 1 | \
    cut -d' ' -f2-
}

copy_if_present() {
  local src="$1"
  local dst="$2"

  if [[ -f "${src}" ]]; then
    cp -f "${src}" "${dst}"
    return 0
  fi

  return 1
}

capture_packaged_workload_metadata() {
  local workload="$1"
  local dest="$2"
  local overlay runner elf image

  overlay="${PYTORCH_CHIPYARD_WORKLOAD_DIR}/overlay-${workload}"
  runner="$(find "${overlay}" -type f -name "run_${workload}.sh" -print -quit 2>/dev/null || true)"
  elf="$(find "${overlay}" -type f -name 'model-*core.elf' -print -quit 2>/dev/null || true)"
  image="${FIREMARSHAL_IMAGE_DIR}/${workload}/${workload}.img"

  [[ -n "${runner}" ]] && copy_if_present "${runner}" "${dest}/packaged-runner.sh" || true
  [[ -n "${elf}" ]] && sha256sum "${elf}" >"${dest}/packaged-elf.sha256" || true
  copy_if_present "${PYTORCH_CHIPYARD_WORKLOAD_DIR}/${workload}.json" \
    "${dest}/firemarshal-workload.json" || true
  copy_if_present "${FIRESIM_WORKLOAD_DIR}/${workload}.json" \
    "${dest}/firesim-workload.json" || true

  {
    printf 'workload=%s\n' "${workload}"
    [[ -n "${elf}" ]] && stat -c 'packaged_elf=%n mtime=%y size=%s' "${elf}"
    [[ -n "${runner}" ]] && stat -c 'packaged_runner=%n mtime=%y size=%s' "${runner}"
    [[ -f "${image}" ]] && stat -c 'firemarshal_image=%n mtime=%y size=%s' "${image}"
  } >"${dest}/packaged-files.txt"
}

capture_firesim_artifact_hashes() {
  local dest="$1"
  local artifacts=()

  while IFS= read -r -d '' artifact; do
    artifacts+=("${artifact}")
  done < <(find "${FIRESIM_RUNS_DIR}" -maxdepth 2 -type f \
    \( -name firesim.tar.gz -o -name driver-bundle.tar.gz \) -print0 2>/dev/null | sort -z)

  if [[ "${#artifacts[@]}" -gt 0 ]]; then
    sha256sum "${artifacts[@]}" >"${dest}/firesim-artifacts.sha256"
  fi
}

uart_has_repeated_corruption() {
  local uart="$1"

  tail -c 65536 "${uart}" 2>/dev/null | \
    od -An -v -tu1 | \
    awk '
      BEGIN { previous = -1; repeated = 0; found = 0 }
      {
        for (i = 1; i <= NF; i++) {
          byte = $i
          if (byte == previous) {
            repeated++
          } else {
            previous = byte
            repeated = 1
          }
          if ((byte == 1 || byte == 255) && repeated >= 4096) {
            found = 1
          }
        }
      }
      END { exit(found ? 0 : 1) }
    '
}

uart_failure_line() {
  local uart line
  local pattern='\*\*\* FAILED \*\*\*|Kernel panic|Oops -|Unhandled fault|unhandled signal|Unable to handle kernel|BUG: unable to handle|Segmentation fault|Illegal instruction|Assertion failed'

  [[ -d "${FIRESIM_RUNS_DIR}" ]] || return 1
  while IFS= read -r -d '' uart; do
    if uart_has_repeated_corruption "${uart}"; then
      printf '%s: at least 4096 repeated 0xff/0x01 bytes in UART output\n' "${uart}"
      return 0
    fi

    line="$(tail -c 1048576 "${uart}" 2>/dev/null | LC_ALL=C strings | grep -E -m1 "${pattern}" || true)"
    if [[ -n "${line}" ]]; then
      printf '%s: %s\n' "${uart}" "${line}"
      return 0
    fi
  done < <(find "${FIRESIM_RUNS_DIR}" -maxdepth 2 -type f -name uartlog -print0 2>/dev/null)

  return 1
}

uart_kernel_failure_line() {
  local uart line
  local pattern='Kernel panic|Oops -|Unable to handle kernel|BUG: unable to handle|Fatal exception in interrupt'

  [[ -d "${FIRESIM_RUNS_DIR}" ]] || return 1
  while IFS= read -r -d '' uart; do
    if uart_has_repeated_corruption "${uart}"; then
      printf '%s: at least 4096 repeated 0xff/0x01 bytes in UART output\n' "${uart}"
      return 0
    fi

    line="$(tail -c 1048576 "${uart}" 2>/dev/null | LC_ALL=C strings | grep -E -m1 "${pattern}" || true)"
    if [[ -n "${line}" ]]; then
      printf '%s: %s\n' "${uart}" "${line}"
      return 0
    fi
  done < <(find "${FIRESIM_RUNS_DIR}" -maxdepth 2 -type f -name uartlog -print0 2>/dev/null)

  return 1
}

failure_text_is_retryable_kernel() {
  local failure="$1"

  case "${failure}" in
    *'Kernel panic'* | *'Oops -'* | *'Unable to handle kernel'* | \
      *'BUG: unable to handle'* | *'Fatal exception in interrupt'* | \
      *'repeated 0xff/0x01 bytes'*)
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

terminate_process_group() {
  local pid="$1"
  local attempt

  kill -TERM -- "-${pid}" 2>/dev/null || kill -TERM "${pid}" 2>/dev/null || true
  for attempt in {1..10}; do
    kill -0 "${pid}" 2>/dev/null || return 0
    sleep 1
  done
  kill -KILL -- "-${pid}" 2>/dev/null || kill -KILL "${pid}" 2>/dev/null || true
}

run_firesim_workload_monitored() {
  local workload="$1"
  local runtime="$2"
  local pid manager_status=0 failure=""

  setsid firesim runworkload \
    -c "${runtime}" \
    -a "${FIRESIM_HWDB_PATH}" \
    -r "${FIRESIM_BUILD_RECIPES_PATH}" &
  pid=$!

  while kill -0 "${pid}" 2>/dev/null; do
    if failure="$(uart_kernel_failure_line)"; then
      warn "${workload}: detected retryable guest kernel failure: ${failure}"
      terminate_process_group "${pid}"
      wait "${pid}" 2>/dev/null || true
      return 70
    fi
    if failure="$(uart_failure_line)"; then
      if failure_text_is_retryable_kernel "${failure}"; then
        warn "${workload}: detected retryable guest kernel failure: ${failure}"
        terminate_process_group "${pid}"
        wait "${pid}" 2>/dev/null || true
        return 70
      fi
      warn "${workload}: detected non-retryable guest failure: ${failure}"
      terminate_process_group "${pid}"
      wait "${pid}" 2>/dev/null || true
      return 71
    fi
    sleep 5
  done

  wait "${pid}" || manager_status=$?

  if failure="$(uart_kernel_failure_line)"; then
    warn "${workload}: detected retryable guest kernel failure: ${failure}"
    return 70
  fi
  if failure="$(uart_failure_line)"; then
    if failure_text_is_retryable_kernel "${failure}"; then
      warn "${workload}: detected retryable guest kernel failure: ${failure}"
      return 70
    fi
    warn "${workload}: detected non-retryable guest failure: ${failure}"
    return 71
  fi

  return "${manager_status}"
}

archive_failed_attempt() {
  local workload="$1"
  local attempt="$2"
  local marker="$3"
  local runtime="${4:-}"
  local dest result_dir uart slot

  dest="${PYTORCH_CHIPYARD_LOG_DIR}/failed-attempts/${workload}/attempt-${attempt}"
  mkdir -p "${dest}"

  result_dir="$(latest_result_dir "${workload}" "${marker}")"
  if [[ -n "${result_dir}" ]]; then
    copy_if_present "${result_dir}/run.log" "${dest}/run.log" || true
    copy_if_present "${result_dir}/workload-config.txt" "${dest}/workload-config.txt" || true
    copy_if_present "${result_dir}/HW_CFG_SUMMARY" "${dest}/HW_CFG_SUMMARY" || true
    if [[ -f "${result_dir}/uartlog" ]]; then
      tail -c 4194304 "${result_dir}/uartlog" >"${dest}/uartlog.tail"
    fi
  fi

  [[ -n "${runtime}" ]] && copy_if_present "${runtime}" "${dest}/config_runtime.yaml" || true
  copy_if_present "${FIRESIM_HWDB_PATH}" "${dest}/config_hwdb.yaml" || true
  copy_if_present "${FIRESIM_BUILD_RECIPES_PATH}" "${dest}/config_build_recipes.yaml" || true
  capture_packaged_workload_metadata "${workload}" "${dest}"
  capture_firesim_artifact_hashes "${dest}"

  while IFS= read -r -d '' uart; do
    slot="$(basename "$(dirname "${uart}")")"
    tail -c 4194304 "${uart}" >"${dest}/${slot}-uartlog.tail"
  done < <(find "${FIRESIM_RUNS_DIR}" -maxdepth 2 -type f -name uartlog -print0 2>/dev/null)

  log "${workload}: archived failed attempt ${attempt} -> ${dest}"
}

validate_workload_result() {
  local workload="$1"
  local result_dir="$2"
  local uart="${result_dir}/uartlog"
  local run_log="${result_dir}/run.log"
  local failure=""

  [[ -f "${uart}" ]] || {
    warn "${workload}: missing uartlog in ${result_dir}"
    return 1
  }
  if uart_has_repeated_corruption "${uart}"; then
    warn "${workload}: repeated 0xff/0x01 bytes indicate corrupt UART output in ${uart}"
    return 70
  fi
  failure="$(tail -c 1048576 "${uart}" 2>/dev/null | LC_ALL=C strings | \
    grep -E -m1 'Kernel panic|Oops -|Unable to handle kernel|BUG: unable to handle|Fatal exception in interrupt' || true)"
  if [[ -n "${failure}" ]]; then
    warn "${workload}: retryable kernel failure found in ${uart}: ${failure}"
    return 70
  fi
  if LC_ALL=C grep -aEq '\*\*\* FAILED \*\*\*|Kernel panic|Oops -|Unhandled fault|unhandled signal|Unable to handle kernel|BUG: unable to handle|Segmentation fault|Illegal instruction|Assertion failed' "${uart}"; then
    warn "${workload}: failure marker found in ${uart}"
    return 1
  fi
  LC_ALL=C grep -aFq '*** PASSED ***' "${uart}" || {
    warn "${workload}: FireSim PASS marker not found in ${uart}"
    return 1
  }
  [[ -s "${run_log}" ]] || {
    warn "${workload}: missing or empty run.log in ${result_dir}"
    return 1
  }
  grep -Fq '[runner] model_ret=0' "${run_log}" || {
    warn "${workload}: model did not return zero according to ${run_log}"
    return 1
  }
  [[ -s "${result_dir}/model.log" ]] || {
    warn "${workload}: missing or empty model.log in ${result_dir}"
    return 1
  }
  [[ -s "${result_dir}/autotune.log" ]] || {
    warn "${workload}: missing or empty autotune.log in ${result_dir}"
    return 1
  }
  if should_collect_output_bin "${workload}"; then
    [[ -s "${result_dir}/output.bin" ]] || {
      warn "${workload}: missing or empty output.bin in ${result_dir}"
      return 1
    }
  fi
}

collect_workload_result() {
  local workload="$1"
  local marker="${2:-}"
  local runtime="${3:-}"
  local result_dir dest entry wall_marker validation_status=0

  result_dir="$(latest_result_dir "${workload}" "${marker}")"
  if [[ -z "${result_dir}" ]]; then
    warn "${workload}: no result directory found under ${PYTORCH_CHIPYARD_RESULTS_WORKLOAD_DIR}"
    return 1
  fi

  validate_workload_result "${workload}" "${result_dir}" || validation_status=$?
  [[ "${validation_status}" -eq 0 ]] || return "${validation_status}"

  dest="$(collected_result_dir "${workload}")"
  mkdir -p "${dest}"
  cp -p -- "${result_dir}/model.log" "${dest}/model.log"
  cp -p -- "${result_dir}/autotune.log" "${dest}/autotune.log"
  cmp -s -- "${result_dir}/model.log" "${dest}/model.log" || return 1
  cmp -s -- "${result_dir}/autotune.log" "${dest}/autotune.log" || return 1

  wall_marker="$(LC_ALL=C grep -aE '^TABLE4_FIRESIM_WALL_S=[0-9]+([.][0-9]+)?$' \
    "${result_dir}/uartlog" | tail -n 1 || true)"
  [[ -z "${wall_marker}" ]] || printf '%s\n' "${wall_marker}"

  while IFS= read -r -d '' entry; do
    case "$(basename "${entry}")" in
      model.log | autotune.log | .completed) ;;
      *) rm -rf -- "${entry}" ;;
    esac
  done < <(find "${dest}" -mindepth 1 -maxdepth 1 -print0)

  log "${workload}: preserved model.log and autotune.log in ${dest}"
}

run_workload() {
  local workload="$1"
  local hw_config="$2"
  local runtime="$3"
  local marker="$4"
  local status=0
  local collect_status=0
  local runworkload_started=0
  local result_path
  local keep_runfarm="${PYTORCH_CHIPYARD_KEEP_RUNFARM:-${KEEP_RUNFARM:-0}}"

  log "${workload}: launchrunfarm/infrasetup/runworkload with ${hw_config}"

  (
    set -euo pipefail
    cd "${FIRESIM_DIR}"
    set +u
    source ./sourceme-manager.sh --skip-ssh-setup
    set -u

    firesim launchrunfarm -c "${runtime}" -a "${FIRESIM_HWDB_PATH}" -r "${FIRESIM_BUILD_RECIPES_PATH}" || status=$?

    if [[ "${status}" -eq 0 ]]; then
      firesim infrasetup -c "${runtime}" -a "${FIRESIM_HWDB_PATH}" -r "${FIRESIM_BUILD_RECIPES_PATH}" || status=$?
    fi

    if [[ "${status}" -eq 0 ]]; then
      runworkload_started=1
      run_firesim_workload_monitored "${workload}" "${runtime}" || status=$?
    fi

    collect_workload_result "${workload}" "${marker}" "${runtime}" || collect_status=$?
    if [[ "${status}" -eq 0 && "${collect_status}" -ne 0 ]]; then
      status="${collect_status}"
    fi

    if [[ "${status}" -ne 0 && "${runworkload_started}" -eq 1 ]]; then
      log "${workload}: cleaning failed FireSim runtime"
      firesim kill -c "${runtime}" -a "${FIRESIM_HWDB_PATH}" -r "${FIRESIM_BUILD_RECIPES_PATH}" || \
        warn "${workload}: firesim kill failed; continuing cleanup"
    fi

    if [[ "${keep_runfarm}" != "1" ]]; then
      firesim terminaterunfarm -c "${runtime}" -a "${FIRESIM_HWDB_PATH}" -r "${FIRESIM_BUILD_RECIPES_PATH}" --forceterminate || true
    fi

    exit "${status}"
  ) || status=$?

  if [[ "${status}" -eq 0 ]]; then
    result_path="$(collected_result_dir "${workload}")"
    pc_stage2_mark_result_complete \
      "${PYTORCH_CHIPYARD_FIGURE_RESULTS_WORKLOAD_DIR}" "${workload}" || \
      return 1
    printf '[firesim-run][PASS] workload=%s model_log=%s autotune_log=%s' \
      "${workload}" "${result_path}/model.log" "${result_path}/autotune.log"
    if [[ -s "${result_path}/output.bin" ]]; then
      printf ' output=%s' "${result_path}/output.bin"
    fi
    printf '\n'
  fi
  return "${status}"
}

SELECTED_WORKLOADS=()
RESUME_MODE=0
RESUME_FROM=""
RVV_PANIC_RETRIES="${PYTORCH_CHIPYARD_RVV_PANIC_RETRIES:-0}"
PREFLIGHT_ONLY=0

while [[ "$#" -gt 0 ]]; do
  case "$1" in
    --workload)
      [[ "$#" -ge 2 ]] || die "--workload requires a value"
      split_workload_arg "$2"
      shift 2
      ;;
    --workload=*)
      split_workload_arg "${1#--workload=}"
      shift
      ;;
    --resume)
      RESUME_MODE=1
      shift
      ;;
    --resume-from)
      [[ "$#" -ge 2 ]] || die "--resume-from requires a value"
      validate_name "workload" "$2"
      RESUME_FROM="$2"
      shift 2
      ;;
    --resume-from=*)
      RESUME_FROM="${1#--resume-from=}"
      validate_name "workload" "${RESUME_FROM}"
      shift
      ;;
    --rvv-panic-retries)
      [[ "$#" -ge 2 ]] || die "--rvv-panic-retries requires a value"
      RVV_PANIC_RETRIES="$2"
      shift 2
      ;;
    --rvv-panic-retries=*)
      RVV_PANIC_RETRIES="${1#--rvv-panic-retries=}"
      shift
      ;;
    --preflight-only)
      PREFLIGHT_ONLY=1
      shift
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      die "unknown argument '$1'; pass --help for usage"
      ;;
  esac
done

[[ "${RVV_PANIC_RETRIES}" == "unlimited" || "${RVV_PANIC_RETRIES}" =~ ^[0-9]+$ ]] || \
  die "invalid --rvv-panic-retries=${RVV_PANIC_RETRIES}; expected a non-negative integer or unlimited"

materialize_default_state_dir() {
  local path="$1" label="$2" old_target=""
  case "${path}" in
    "${PYTORCH_CHIPYARD_STATE_DIR}" | "${PYTORCH_CHIPYARD_STATE_DIR}"/*) ;;
    *) mkdir -p "${path}"; return ;;
  esac
  if [[ -L "${path}" ]]; then
    old_target="$(readlink -f -- "${path}" 2>/dev/null || true)"
    rm -f -- "${path}"
    log "replaced legacy ${label} symlink with ${path}"
    case "${old_target}" in
      "${WORKSPACE}/.firesim-runtime" | "${WORKSPACE}/FIRESIM_RUNS_DIR")
        rm -rf -- "${old_target}"
        ;;
    esac
  fi
  [[ ! -e "${path}" || -d "${path}" ]] || die "${label} is not a directory: ${path}"
  mkdir -p "${path}"
}

materialize_default_state_dir "${FIRESIM_RUNS_DIR}" FIRESIM_RUNS_DIR
materialize_default_state_dir \
  "${PYTORCH_CHIPYARD_FIRESIM_RUNTIME_DIR}" \
  PYTORCH_CHIPYARD_FIRESIM_RUNTIME_DIR

require_dir "${FIRESIM_DIR}"
mkdir -p "${FIRESIM_DEPLOY_DIR}" "${FIRESIM_WORKLOAD_DIR}" \
  "${PYTORCH_CHIPYARD_RESULTS_WORKLOAD_DIR}" "${FIRESIM_RUNS_DIR}" \
  "${PYTORCH_CHIPYARD_FIRESIM_RUNTIME_DIR}"
if [[ "${PREFLIGHT_ONLY}" != "1" || "${#SELECTED_WORKLOADS[@]}" -eq 0 ]]; then
  require_dir "${FIRESIM_WORKLOAD_DIR}"
fi

FIRESIM_PYTHON="$(resolve_firesim_python)"
log "FireSim Python: ${FIRESIM_PYTHON} ($("${FIRESIM_PYTHON}" --version 2>&1))"
prepare_firesim_hwdb

WORKLOADS=()
load_workloads
apply_resume_filters
validate_pending_workload_packages
declare -A WORKLOAD_HW_CONFIGS=()
declare -A VALIDATED_HW_CONFIGS=()
for workload in "${WORKLOADS[@]}"; do
  hw_config="$(infer_hw_config "${workload}")"
  validate_required_hw_config "${workload}" "${hw_config}"
  WORKLOAD_HW_CONFIGS["${workload}"]="${hw_config}"
  if [[ -z "${VALIDATED_HW_CONFIGS[${hw_config}]:-}" ]]; then
    require_hw_config "${hw_config}"
    VALIDATED_HW_CONFIGS["${hw_config}"]=1
  fi
  log "${workload}: selected hardware config ${hw_config}"
done
if [[ "${PREFLIGHT_ONLY}" == "1" ]]; then
  printf 'FIRESIM_HWDB_PREFLIGHT_STATUS=PASS\n'
  exit 0
fi

runtime_cleanup_on_exit() {
  local status=$?
  local cleanup_status=0
  local workload
  local -a cleanup_args=()

  trap - EXIT
  if [[ "${#WORKLOADS[@]}" -eq 0 ]]; then
    cleanup_args+=(--all)
  else
    for workload in "${WORKLOADS[@]}"; do
      cleanup_args+=(--workload "${workload}")
    done
  fi
  if [[ "${PYTORCH_CHIPYARD_DEFER_FINAL_CLEANUP:-0}" != "1" ]]; then
    cleanup_args+=(--final)
  fi
  bash "${SCRIPT_DIR}/cleanup-runtime-artifacts.sh" "${cleanup_args[@]}" || cleanup_status=$?
  if [[ "${cleanup_status}" -ne 0 ]]; then
    warn "runtime cleanup failed with status ${cleanup_status}"
    [[ "${status}" -ne 0 ]] || status="${cleanup_status}"
  fi
  exit "${status}"
}
trap runtime_cleanup_on_exit EXIT

for workload in "${WORKLOADS[@]}"; do
  validate_rvv_success_package "${workload}"
done
clean_collected_results

require_file "${FIRESIM_DIR}/sourceme-manager.sh"
fpga_db="${PYTORCH_CHIPYARD_FPGA_DB}"
require_file "${fpga_db}"
log "FPGA DB: ${fpga_db}"

for workload in "${WORKLOADS[@]}"; do
  hw_config="${WORKLOAD_HW_CONFIGS[${workload}]}"
  runtime="$(generate_runtime_config "${workload}" "${hw_config}" "${fpga_db}")"
  marker="${PYTORCH_CHIPYARD_FIRESIM_RUNTIME_DIR}/.${workload}.run-start"
  mkdir -p "$(dirname "${marker}")"
  rm -f "$(collected_result_dir "${workload}")/.completed"
  attempt=1
  while true; do
    clean_firesim_runs_dir
    : >"${marker}"
    if run_workload "${workload}" "${hw_config}" "${runtime}" "${marker}"; then
      clean_completed_firesim_run
      break
    else
      status=$?
    fi
    if contains_tag "${workload}" "rvv" && [[ "${status}" -eq 70 ]]; then
      if [[ "${RVV_PANIC_RETRIES}" == "unlimited" || \
          "${attempt}" -le "${RVV_PANIC_RETRIES}" ]]; then
        log "${workload}: retrying after kernel failure (${attempt}/${RVV_PANIC_RETRIES})"
        attempt=$((attempt + 1))
        continue
      fi
    fi
    die "${workload}: failed with status ${status}; stopping before the next workload infrasetup"
  done
done

printf 'FIRESIM_RESULTS_DIR=%s\n' "${PYTORCH_CHIPYARD_FIGURE_RESULTS_WORKLOAD_DIR}"
printf 'FIRESIM_STATUS=PASS\n'
